# Server configuration
server.port=8080

# Database configuration (Supabase PostgreSQL via Session Pooler - IPv4 compatible)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.saeieulilltuqqkqrcoy
spring.datasource.password=ngkmSn85?!@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Supabase Storage configuration
supabase.url=https://saeieulilltuqqkqrcoy.supabase.co
supabase.service.role.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZWlldWxpbGx0dXFxa3FyY295Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDg1MjM4NywiZXhwIjoyMDkwNDI4Mzg3fQ.FGFDH9oJyDdKf0Ibbbnv9wUkje4YlyQA_VJ5ruSLGug
supabase.bucket.name=documents

# AI Configuration (Google Gemini)
ai.api.key=AIzaSyAL7qIBM5g9ElJnZjXUwmR7NYQrAESdZjk
ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
ai.model=gemini-flash-latest

# File Upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Activate local profile by default
spring.profiles.active=local

